version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.10
jobs:
  test:
    docker:
      - image: circleci/golang:1.13.4
    working_directory: ~/go/src/test
    steps:
      - checkout
      - run:
          name: Go get library
          #command: go get -u -t -v -d ./...
          command: go get github.com/gin-gonic/gin && go get github.com/jinzhu/gorm && go get github.com/go-sql-driver/mysql && go get golang.org/x/tools/cmd/goimports && go get github.com/joho/godotenv && go get golang.org/x/crypto/bcrypt && go get github.com/google/uuid && go get github.com/aws/aws-sdk-go/aws && go get github.com/aws/aws-sdk-go/aws/session && go get github.com/aws/aws-sdk-go/service/ses && go get github.com/bamzi/jobrunner && go get github.com/k-washi/jwt-decode/jwtdecode && go get firebase.google.com/go && go get github.com/gin-contrib/cors && go get github.com/kemper0530/go-handson-lambda/common && go get github.com/kemper0530/go-handson-lambda/config && go get github.com/kemper0530/go-handson-lambda/controllers/controller && go get github.com/stretchr/testify/assert && go get google.golang.org/api/option && go get github.com/aws/aws-lambda-go/events && go get github.com/aws/aws-lambda-go/lambda && go get github.com/awslabs/aws-lambda-go-api-proxy/gin
      - run:
          name: Env Setup
          command: echo 'export PATH=/go/bin/:${PATH}' >> $BASH_ENV
      - run:
          name: Run Test
          command: GO_ENV=development go test -cover -v
  # EC2にSSH接続し、コンテナを実行
    # machine:
    #   image: circleci/classic:edge
    # steps:
    #   # CircleCIに登録した秘密鍵を呼び出す。
    #   - add_ssh_keys:
    #       fingerprints:
    #         - "46:4c:fd:fd:5f:a4:25:e4:a1:0e:be:a6:18:d5:98:32"
    #   - run:
    #       name: AWS Login
    #       command: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 870574718611.dkr.ecr.ap-northeast-1.amazonaws.com
    #   - run:
    #       name: build
    #       command: docker build -t go-handson-lambda .
    #   - run:
    #       name: tag
    #       command: docker tag go-handson-lambda:latest 870574718611.dkr.ecr.ap-northeast-1.amazonaws.com/go-handson-lambda:latest
    #   - run:
    #       name: docker push
    #       command: docker push 870574718611.dkr.ecr.ap-northeast-1.amazonaws.com/go-handson-lambda:latest
    #   # - run:
      #     name: sleep 60s
      #     command: sleep 60
      # - run:
      #     name: actuator
      #     command: curl -X GET https://api.kemper0530.com/V1/actuaterHealth
workflows:
  version: 2
  test_and_build_and_deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_REGION}
          tag: "${CIRCLE_SHA1}"
          requires:
            - test
          filters:
            branches:
              only: master
